# @package model

defaults:
  - training_config: ddpm.yaml

_target_: src.models.ddpm_generator.DDPMModule
_recursive_: False
model_config:
  netG:
    _target_: src.models.components.generators.vsa_generator.VSGenerator
    input_channels: 3
    output_channels: 3
    ida_channels: 64
    channels: [16, 32, 64, 128, 256, 512]
    head_channels: [64, 32]
    levels: [1, 1, 1, 2, 2, 1]
    norm_name: group
    pool_name: max
    apply_tanh: False

  img_size: 128  # Saved only for additional use

  norm:
    mean: [ 0.5, 0.5, 0.5 ]
    std: [ 0.5, 0.5, 0.5 ]

  # Train specific parameters
  scheduling:
    num_steps: 1000
    start_beta: 0.0001
    end_beta: 0.02