# https://wandb.ai

wandb:
  _target_: pytorch_lightning.loggers.wandb.WandbLogger
  project: VSDiffusion_${task_name}
  name: ${name}_${git_id}
  save_dir: "${paths.output_dir}"
  offline: False
  id: ${name}_${git_id} # pass correct id to resume experiment!
  log_model: False # upload lightning ckpts
  prefix: "" # a string to put at the beginning of metric keys
  # entity: "" # set to name of your wandb team
  group: ""
  tags: []
  job_type: "train"
